In [2]:
import pandas as pd

In [3]:
ld_train = pd.read_csv('loan_data_train.csv')

In [4]:
ld_train

,ID,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length
0,79542.0,25000,25000,18.49%,60 months,debt_consolidation,27.56%,VA,MORTGAGE,8606.56,720-724,11,15210,3.0,5 years
1,75473.0,19750,19750,17.27%,60 months,debt_consolidation,13.39%,NY,MORTGAGE,6737.50,710-714,14,19070,3.0,4 years
2,67265.0,2100,2100,14.33%,36 months,major_purchase,3.50%,LA,OWN,1000.00,690-694,13,893,1.0,< 1 year
3,80167.0,28000,28000,16.29%,36 months,credit_card,19.62%,NV,MORTGAGE,7083.33,710-714,12,38194,1.0,10+ years
4,17240.0,24250,17431.82,12.23%,60 months,credit_card,23.79%,OH,MORTGAGE,5833.33,730-734,6,31061,2.0,10+ years
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,74047.0,30000,30000,23.28%,60 months,other,12.10%,IL,MORTGAGE,7083.33,675-679,16,17969,1.0,10+ years
2196,63768.0,4200,4200,14.33%,60 months,car,14.16%,NJ,RENT,3850.00,700-704,4,5718,0.0,2 years
2197,94545.0,19800,19775,15.31%,60 months,debt_consolidation,15.03%,IL,MORTGAGE,6666.67,675-679,10,46879,3.0,6 years
2198,53635.0,18000,18000,20.99%,60 months,credit_card,11.63%,CA,RENT,9051.83,670-674,5,32394,2.0,4 years
2199,67953.0,7550,7550,10.16%,36 months,debt_consolidation,3.83%,CA,MORTGAGE,8333.33,710-714,10,10204,0.0,2 years

In [5]:
ld_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID                              2199 non-null   float64
 1   Amount.Requested                2199 non-null   object
 2   Amount.Funded.By.Investors      2199 non-null   object
 3   Interest.Rate                   2200 non-null   object
 4   Loan.Length                     2199 non-null   object
 5   Loan.Purpose                    2199 non-null   object
 6   Debt.To.Income.Ratio            2199 non-null   object
 7   State                           2199 non-null   object
 8   Home.Ownership                  2199 non-null   object
 9   Monthly.Income                  2197 non-null   float64
 10  FICO.Range                      2200 non-null   object
 11  Open.CREDIT.Lines               2196 non-null   object
 12  Revolving.CREDIT.Balance        2197 non-null   object
 13  Inquiries.in.the.Last.6.Months  2197 non-null   float64
 14  Employment.Length               2131 non-null   object
dtypes: float64(3), object(12)
memory usage: 257.9+ KB

In [6]:
### Insights and Data Cleaning and Processing
## We need to ignore ID as it is not useful for prediction

In [7]:
ld_train['Loan.Length'].value_counts(dropna=False)

Loan.Length
36 months    1722
60 months     476
NaN             1
.               1
Name: count, dtype: int64

In [8]:
ld_train['Loan.Purpose'].value_counts(dropna=False)

Loan.Purpose
debt_consolidation    1147
credit_card            394
other                  174
home_improvement       135
major_purchase          84
small_business          80
car                     45
wedding                 35
medical                 26
moving                  25
house                   19
vacation                18
educational             14
renewable_energy         3
NaN                      1
Name: count, dtype: int64